version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:5.7.41
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  pythonapp:
    restart: always
    container_name: "pythonapp"
    build: .
    depends_on:
      - mysql
    links:
      - mysql:mysql